<?php

function management_center_home_page_display() {
    $page_content = '';
    $page_content .= '';

    return $page_content;
}

function management_center_login_page_display() {
    $page_content = '';
    $page_content .= '';

    return $page_content;
}

function management_center_topic_upload_page_display() {
    $page_content = '';
    $page_content .= '';

    return $page_content;
}


?>
