<?php

function dxf_general_menu() {
    $items['home'] = array(
        'title' => 'Home page',
        'type' => MENU_CALLBACK,
        'page callback' => 'home_page_display',
        'page arguments' => array(),
        'access callback' => TRUE,
        'file' => 'dxf_general.inc',
    );
    
    $items['imagewall'] = array(
        'title' => 'Image gallery wall',
        'type' => MENU_CALLBACK,
        'page callback' => 'image_wall_display',
        'page arguments' => array(),
        'access callback' => TRUE,
        'file' => 'dxf_general.inc',
    );
    
    $items['topic'] = array(
        'title' => 'Featured topic',
        'type' => MENU_CALLBACK,
        'page callback' => 'featured_topic_display',
        'page arguments' => array(),
        'access callback' => TRUE,
        'file' => 'dxf_general.inc',
    );
    
    $items['topic/%'] = array(
        'title' => 'Featured topic detail',
        'type' => MENU_CALLBACK,
        'page callback' => 'featured_topic_detail_display',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'file' => 'dxf_general.inc',
    );
    
    return $items;
}
?>
